---
title: "Mi libro con bookdown"
author: "Tu nombre"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output: bookdown::gitbook
---


# Introdución
Este es el primer capítulo de tu libro .



## Justificación.

Dentro de los mercados financieros donde la volatilidad es parte de su naturaleza, el mercado de las criptomonedas sobresale por ser altamente voluble con alta incertidumbre en función de sus proyecciones y predicciones. Esto se da principalmente porque es un mercado no regulado que opera las 24 horas del día en los 7 días de la semana.

Según TradingView (s.f.), la dominancia de Bitcoin en el mercado de criptomonedas es de más del 50%, lo que lo hace el dominador del mercado. Es por ello, el interés de realizar el estudio de series de tiempo a esta criptomoneda desde un enfoque univariado.


Para este estudio se propone realizar análisis de serie para:

1.	Periodo diario: Desde 01 de enero de 2022 al 27 de abril de 2025.
2.	Se evaluará diferentes modelos estadísticos y de machine learning en busca del modelo que mejor ajuste al comportamiento del mercado.

## Fuente de información.

Para el propósito del presente estudio se conectará directamente a la fuente de datos de yahoo binance por medio del paquete ZOO de r. tanto el paquete como la información de yahoo finance es libre y no tiene restricciones para su uso.

el periodo ha evaluar es del 1 de enero de 2018 al 27 de abril de 2025.
